import { defineConfig } from "drizzle-kit";

// Source of truth for OUR tables only. pg-boss owns its own schema (pgboss)
// and the legacy raw migrations left a public.schema_migrations table behind,
// so the filters keep drizzle-kit from trying to manage anything but these.
export default defineConfig({
  dialect: "postgresql",
  schema: "./db/schema.ts",
  out: "./db/drizzle",
  dbCredentials: {
    url: process.env.DATABASE_URL ?? "",
  },
  schemaFilter: ["public"],
  tablesFilter: [
    "agent_scheduled_tasks",
    "agent_scheduled_task_runs",
    "agent_skills",
    "agent_chat_sessions",
    "agent_chat_messages",
    "agent_memory_documents",
    "agent_trace_artifacts",
    "agent_trace_events",
    "agent_memory_candidates",
    "agent_memory_candidate_trace_events",
    "agent_decisions",
    "agent_decision_trace_events",
    "agent_outcomes",
    "agent_outcome_trace_events",
    "agent_memories",
    "agent_memory_versions",
    "agent_memory_version_trace_events",
    "agent_profiles",
    "agent_profile_versions",
    "agent_profile_version_sources",
    "agent_profile_fact_tombstones",
    "agent_profile_synthesis_receipts",
    "agent_review_proposals",
    "agent_review_states",
    "agent_grounded_observations",
    "agent_recall_signals",
    "agent_phase_signals",
    "agent_ingestion_checkpoints",
    "agent_memory_snapshots",
    "agent_consolidation_settings",
    "agent_consolidation_runs",
    "agent_consolidation_candidates",
    "agent_memory_events",
  ],
});
